import { characters } from "app/bartholomew-faire";

export const PLAY = {
  characters: {
    littlewit: { name: 'Littlewit', description: 'The ecclesiastical lawyer who issues Cokes\'s marriage license, and author of the puppet show'},
    winthefight: { name: 'Win-the-Fight', description: 'Littlewit\'s wife and Dame Purecraft\'s daughter. Win fakes a pregnancy craving to get her strict Puritan mother to agree to let her go to the fair.'},
    winwife: { name: 'Winwife', description: 'A widow-hunter and friend of Littlewit\'s. He begins the play in pursuit of Dame Purecraft' },
    quarlous: { name: 'Quarlous', description: 'A provocateur and friend of both Winwife and Littlewit' },
    wasp: { name: 'Wasp', description: 'Cokes\'s irascible and rude tutor' },
    cokes: { name: 'Cokes', description: 'A man-child engaged to Grace Wellborn, brother to Mistress Overdo. He is the target of a number of thefts throughout.' },
    grace: { name: 'Grace', description: 'The ward of Justice Overdo who, because of a controversial law, must either marry the man Overdo selects (Cokes) or pay a hefty fine' },
    mistressoverdo: { name: 'Dame Overdo', description: 'Justice Overdo\'s wife and Cokes\'s sister. She accompanies Grace and Cokes to the fair },
    solomon: { name: 'Solomon', description: 'servant to Littlewit' },
    damepurecraft: { name: 'Dame Purecraft', description: 'A Puritan with a streak of superstition. She is well off and being courted both by the young Winwife and Zeal-of-the-Land Busy, her religious leader. A fortune-teller tells her before the start of the play that she must marry a madman within the next week in order to be happy.' },
    zealoftheland: { name: 'Busy', description: 'A hypocritical Puritan who claims to hate the pleasures of the fair' },
    busy: { name: 'Busy', description: 'A hypocritical Puritan who claims to hate the pleasures of the fair' },
    overdo: { name: 'Justice Overdo', description: 'A judge who goes undercover as the madman Arthur Bradley in order to uncover behavior at the fair' },
    leatherhead: { name: 'Leatherhead', description: 'A puppeteer and fair worker' },
    trash: { name: 'Trash', description: 'A fair worker selling gingerbread' },
    ursula: { name: 'Ursula', description: 'A fair worker selling pig and ale' },
    mooncalf: { name: 'Mooncalf', description: 'Ursula\'s servant },
    costermonger: { name: 'Costermonger', description: 'A fruit seller' },
    knockem: { name: 'Knockem', description: 'A horse courser, a profession with a reputation similar to the stereotype of a crooked used-car salesman' },
    edgworth: { name: 'Edgworth', description: 'A thief' },
    nightingale: { name: 'Nightingale', description: 'A thief who sings to provide distraction for Edgworth description' },
    corncutter: { name: 'Corncutter', description: 'A patron at Ursula\'s booth who offers to cut the corns from people\'s feet' },
    tinderboxman: { name: 'Tinderbox Man', description: 'character description' },
    passengers: { name: 'Passengers', description: 'character description' },
    whit: { name: 'Capt Whit', description: 'character description' },
    haggis: { name: 'Haggis', description: 'character description' },
    bristle: { name: 'Bristle', description: 'character description' },
    troubleall: { name: 'Trouble All', description: 'character description' },
    mistresslittlewit: { name: 'Mistress Littlewit', description: 'character description' },
    poacher: { name: 'Poacher', description: 'character description' },
    nordern: { name: 'Nordern', description: 'character description' },
    puppy: { name: 'Puppy', description: 'character description' },
    cutting: { name: 'Cutting', description: 'character description' },
    alice: { name: 'Alice', description: 'character description' },
    filcher: { name: 'Filcher', description: 'character description' },
    sharkwell: { name: 'Sharkwell', description: 'character description' },
    puppetleander: { name: 'Puppet Leander', description: 'character description' },
    puppetcole: { name: 'Puppet Cole', description: 'character description' },
    puppetjonas: { name: 'Puppet Jonas', description: 'character description' },
    puppetdamon: { name: 'Puppet Damon', description: 'character description' },
    puppetpythias: { name: 'Puppet Pythias', description: 'character description' }
  }
}
