import { characters } from "app/bartholomew-faire";

export const PLAY = {
  characters: {
    littlewit: { name: 'Littlewit', description: 'The ecclesiastical lawyer who issues Cokes\'s marriage license, and author of the puppet show'},
    winthefight: { name: 'Win-the-Fight', description: 'Littlewit\'s wife and Dame Purecraft\'s daughter.'},
    winwife: { name: 'Winwife', description: 'A widow-hunter and friend of Littlewit\'s. He begins the play in pursuit of Dame Purecraft' },
    quarlous: { name: 'Quarlous', description: 'A provocateur and friend of both Winwife and Littlewit' },
    wasp: { name: 'Wasp', description: 'Cokes\'s irascible and rude tutor' },
    cokes: { name: 'Cokes', description: 'A man-child engaged to Grace Wellborn, brother to Mistress Overdo.' },
    grace: { name: 'Grace', description: 'The ward of Justice Overdo who, because of a controversial law, must either marry the man Overdo selects (Cokes) or pay a hefty fine' },
    mistressoverdo: { name: 'Dame Overdo', description: 'Justice Overdo\'s wife and Cokes\'s sister. She accompanies Grace and Cokes to the fair' },
    solomon: { name: 'Solomon', description: 'servant to Littlewit' },
    damepurecraft: { name: 'Dame Purecraft', description: 'A Puritan with a streak of superstition. She is well off and being courted both by the young Winwife and Zeal-of-the-Land Busy, her religious leader. A fortune-teller tells her before the start of the play that she must marry a madman within the next week in order to be happy.' },
    zealoftheland: { name: 'Busy', description: 'A hypocritical Puritan who claims to hate the pleasures of the fair' },
    busy: { name: 'Busy', description: 'A hypocritical Puritan who claims to hate the pleasures of the fair' },
    overdo: { name: 'Justice Overdo', description: 'A judge who goes undercover as the madman Arthur Bradley in order to uncover bad behavior at the fair' },
    leatherhead: { name: 'Leatherhead', description: 'A puppeteer and fair worker' },
    trash: { name: 'Trash', description: 'A fair worker selling gingerbread' },
    ursula: { name: 'Ursula', description: 'A fair worker selling pig and ale' },
    mooncalf: { name: 'Mooncalf', description: 'A fair worker and Ursula\'s servant' },
    costermonger: { name: 'Costermonger', description: 'A fruit seller' },
    knockem: { name: 'Knockem', description: 'A horse courser, someone who buys and sells horses'},
    edgworth: { name: 'Edgworth', description: 'A thief' },
    nightingale: { name: 'Nightingale', description: 'A thief who sings to provide distraction for Edgworth' },
    corncutter: { name: 'Corncutter', description: 'A customer at Ursula\'s booth who offers to cut the corns from people\'s feet' },
    tinderboxman: { name: 'Tinderbox Man', description: 'One of Ursula\'s customers' },
    passengers: { name: 'Passengers', description: 'One of Ursula\'s customers' },
    whit: { name: 'Capt Whit', description: 'A pimp who convinces Win and Mistress Overdo to dress up and who offers to sell their sexual favors' },
    haggis: { name: 'Haggis', description: 'A member of the watch' },
    bristle: { name: 'Bristle', description: 'A member of the watch' },
    troubleall: { name: 'Trouble All', description: 'A madman. Insists upon a warrant, signed in Overdo\'s name, before taking any action' },
    mistresslittlewit:  { name: 'Win-the-Fight', description: 'Littlewit\'s wife and Dame Purecraft\'s daughter. Win fakes a pregnancy craving to get her strict Puritan mother to agree to let her go to the fair.'},
    poacher: { name: 'Poacher', description: 'A fairgoer' },
    nordern: { name: 'Nordern', description: 'A fairgoer' },
    puppy: { name: 'Puppy', description: 'A fairgoer and wrestler from the western part of England' },
    cutting: { name: 'Cutting', description: 'A delinquent' },
    alice: { name: 'Alice', description: 'Mistress of prostitution who is angered by Whit's competition },
    filcher: { name: 'Filcher', description: 'A fairgoer' },
    sharkwell: { name: 'Sharkwell', description: 'A fairgoer' },
    puppetleander: { name: 'Puppet Leander', description: 'A puppet who plays the lead love interest of the final puppet show' },
    puppetcole: { name: 'Puppet Cole', description: 'A puppet who plays role of sculler, or oarsman' },
    puppetjonas: { name: 'Puppet Jonas', description: 'A puppet' },
    puppetdamon: { name: 'Puppet Damon', description: 'A puppet who competes for Hero against his friend Pythias' },
    puppetpythias: { name: 'Puppet Pythias', description: 'A puppet who competes for Hero against his friend Damon' }
  }
}
